### PR TITLE
Make and test with coverage

### PR DESCRIPTION
**Pull request by hugovk**
For https://github.com/python-pillow/docker-images/issues/11.

Needs Pillow to be built with CFLAGS="-coverage", for example like https://github.com/python-pillow/Pillow/pull/2781.

### CODE REVIEW

**Comment by wiredfool** [comment]
* This needs to have the various other python modules installed to do coverage. 
```
RUN virtualenv -p /usr/bin/python2.7 --system-site-packages /vpy && \
    /vpy/bin/pip install nose cffi olefile nose-cov coverage coveralls cov-core && \
    chown -R pillow:pillow /vpy
```
* `python ./test-installed.py -v --with-coverage` doesn't appear to write coverage for the c layer.

**Comment by hugovk** [comment]
This branch now pip installs coverage modules.

This branch -- https://travis-ci.org/hugovk/docker-images/builds/287937280 -- is the same but has an updated Pillow submodule which includes the `make install-coverage` command from https://github.com/python-pillow/Pillow/pull/2781.

Here's a build from that: https://travis-ci.org/hugovk/docker-images/builds/287937280

All are passing apart from three:
* arch: [FAIL: TestFileEps.test_showpage](https://travis-ci.org/hugovk/docker-images/jobs/287937282#L3202)
* amazon-amd64: [/bin/sh: useradd: command not found](https://travis-ci.org/hugovk/docker-images/jobs/287937283#L1140)
* ubuntu-trusty-x86: [FAIL: TestFontPcf.test_high_characters](https://travis-ci.org/hugovk/docker-images/jobs/287937287#L5419)

Comparing with [a docker-images master build](https://travis-ci.org/hugovk/docker-images/builds/287940569):
* amazon-amd64: fails in the same way

Anyway, checking just a passing ones for now:

* https://travis-ci.org/hugovk/docker-images/jobs/287937281 shows it is running with coverage! It's covering some non-PIL stuff, and this can be restricted.

**Comment by wiredfool** [comment]
Looks like Amazon has stripped a bunch out of their amazon linux images, and the dependencies for xvfb haven't been updated. I've fixed that with my pr_12 branch.

**Comment by hugovk** [comment]
This PR needs updating for pytest too, re: https://github.com/python-pillow/Pillow/pull/2815.

**Comment by wiredfool** [comment]
Yes, but the things that are holding it up right now are orthogonal to the pytest issue.

**Comment by wiredfool** [comment]
Pushing the images now.

**Pull request merged**
