### PR TITLE
Fix case for Docker command

### PR DESCRIPTION
**Pull request by coliss86**

### CODE REVIEW

**Comment by wiredfool** [comment]
Please don’t leave junk PRs for digital oceans thing.

**Comment by gmembre-zenika** [comment]
I opened this PR because there is a mistake in the Dockerfile. Docker command must be written in upper case, as in the rest of this file.

This is not spam, it is about quality

**Comment by coliss86** [comment]
I opened this PR because there is a mistake in the Dockerfile. Docker command must be written in upper case, as in the rest of this file.

This is not spam, it is about quality

**Comment by hugovk** [comment]
I think this one is okay. 

> The instruction is not case-sensitive. However, convention is for them to be UPPERCASE to distinguish them from arguments more easily.

https://docs.docker.com/engine/reference/builder/

Are all the rest consistent in other files?

**Comment by wiredfool** [comment]
No, they’re not consistent.

It’s a one word change that partially fixes a non problem with no explanation when there’s a rash of other spam PRs out there, from someone who has sent similar PRs to four unrelated repos.

On the plus side, it’s not just adding an emoji.

**Comment by coliss86** [comment]
Good to know, never saw in lower case.

At least thoses files have also lower case commands : 
https://github.com/python-pillow/docker-images/blob/master/amazon-2-amd64/Dockerfile
https://github.com/python-pillow/docker-images/blob/master/centos-6-amd64/Dockerfile

Would like a PR with all command in upper case ?

What's the point with emoji ?

**Pull request closed without merging**
