### PR TITLE
Fedora-27

### PR DESCRIPTION
**Pull request by wiredfool**
Fedora 27 is now available, however it ships with webp 0.6.1, which fails a test.

### CODE REVIEW

**Comment by hugovk** [comment]
I wonder why this didn't trigger a Travis build.
https://travis-ci.org/python-pillow/docker-images/pull_requests

**Comment by wiredfool** [comment]
Wouldn't have worked anyway, as there would have been a test failure. I've pushed a new commit with the new pointer to master, and it looks like it's going now.

**Comment by hugovk** [comment]
Looks good to merge, but this now has a conflict after merging the other.

**Comment by wiredfool** [comment]
Yah, they both modified the same line. It's fixed now.

**Pull request merged**
