### PR TITLE
Merge 3 git commands into one

### PR DESCRIPTION
**Pull request by tuannh99**
Small update to README.md.

Just to merge 3 git commands into one.

### CODE REVIEW

**Comment by hugovk** [comment]
Does https://github.com/python-pillow/docker-images/blob/master/update-pillow-tag.sh need updating?

**Comment by radarhere** [comment]
It's not exactly the same, because it lacks the clone command, but we can do #107

**Comment by tnguyenns1** [comment]
Yeah #107 works.
Thanks @radarhere

**Comment by tuannh99** [comment]
Yeah #107 works.
Thanks @radarhere.

**Pull request merged**
