### PR TITLE
Only attempt push if credentials available

### PR DESCRIPTION
**Pull request by hugovk**
`master` builds fail on my fork because it attempts to push the image:

image

* https://github.com/hugovk/docker-images/runs/1444438200?check_suite_focus=true

Instead, skip the push for forks.

Passing fork `master` with this change:

image

* https://github.com/hugovk/docker-images/actions/runs/379927580

### CODE REVIEW

**Comment by nulano** [comment]
I would like to be able to still push to my Docker account, e.g. to test the Arm64 builds if I get around to them. Can you try my version from https://github.com/nulano/docker-images/tree/master which only skips if the login failed? (It seems using `secrets.*` is not allowed in the `if` condition.)

**Comment by hugovk** [comment]
Updated! 

https://github.com/hugovk/docker-images/actions/runs/380946241 is running.

**Comment by hugovk** [comment]
And successfully skipped 👍 

image

**Comment by nulano** [comment]
> And successfully skipped 👍

It's also successfully pushing on mine: https://github.com/nulano/docker-images/runs/1447228597?check_suite_focus=true#step:6:78

**Pull request merged**
