### PR TITLE
Add Mergify config

### PR DESCRIPTION
**Pull request by hugovk**
For https://github.com/python-pillow/Pillow/issues/4900.

This has these rules:

* approved by more than one person
* has `automerge` label
* Travis CI has passed

Note that you cannot approve your own PR. And the rules for GHA is a little different than Travis, so let's with the simpler repo.

Docs for reference: https://doc.mergify.io/actions.html#actions

# To test

When the CI is still running (or if it finished already, restart a job or the whole thing), approve and add the `automerge` label.

It should merge once the CI finishes.

### CODE REVIEW

**Comment by hugovk** [comment]
Actually, I removed this push rule, because the push happened on my fork, and only the PR one is visible here:

```yml
      - status-success=continuous-integration/travis-ci/push
```

**Comment by hugovk** [comment]
@radarhere Please could you test this? Thank you!

**Review by radarhere — APPROVED** [review]

**Comment by radarhere** [comment]
Did you mean like that, by approving and labelling? I guess it doesn't apply until it is actually merged.

**Comment by radarhere** [comment]
If you want a PR to test it on, I can offer you #85

**Comment by hugovk** [comment]
> Did you mean like that, by approving and labelling? I guess it doesn't apply until it is actually merged.

Yes. Could be, will merge and test with #85. Thanks!

**Pull request merged**
