### PR TITLE
Add numpy

### PR DESCRIPTION
**Pull request by homm**

### CODE REVIEW

**Comment by hugovk** [comment]
Build blocked by https://github.com/python-pillow/docker-images/pull/24.

**Comment by homm** [comment]
If I understand correctly, this will significantly increase test time for platforms without numpy binary wheels. Also, compilation fails at least on amazon-2. Is it a way to install numpy system-wide and use it in venv?

**Comment by wiredfool** [comment]
I haven't been too concerned with getting every feature tested on every platform, especially for things where we're installing a specific version from pip. I'm more worried about getting the system versions of libraries tested in the docker files. So, I'd say that we should use system package numpy when possible, binary wheels if not, and skip it if we've got to compile it.

**Comment by homm** [comment]
@wiredfool Do you think is it a blocker for https://github.com/python-pillow/Pillow/pull/3099?

**Comment by hugovk** [comment]
This need not block https://github.com/python-pillow/Pillow/pull/3099, as long as NumPy is being tested somewhere (and it is, in "native" Linux builds as part of that PR).

**Comment by hugovk** [comment]
@homm Would you like to modify this so NumPy is only installed on those that have wheels?

It's also good to test the code paths without NumPy installed.

**Comment by hugovk** [comment]
Please see PR #56 for an update of this.

**Pull request closed without merging**
