### PR TITLE
Added Ubuntu 24.04

### PR DESCRIPTION
**Pull request by radarhere**
Ubuntu 24.04 has been released - https://releases.ubuntu.com/noble/

Transitioning to the new Ubuntu meant updating to Python 3.12, and adding libxcb-shape0 for PySide6, but also, an error started appearing from `addgroup pillow sudo`
https://github.com/radarhere/docker-images/actions/runs/8857703276/job/24325472410#step:6:2293
> fatal: addgroup with two arguments is an unspecified operation.

Removing the command then led to a permission error during install - it turns out that our use of 1000 as the pillow user id
https://github.com/python-pillow/docker-images/blob/03bcc464deccdb2cf73279be1bc31d3d19f6d521/.github/workflows/build.yml#L72
doesn't work on Ubuntu 24.04. It has moved from [1000](https://github.com/radarhere/docker-images/actions/runs/8857639618/job/24325344593#step:6:2185) to [1001](https://github.com/radarhere/docker-images/actions/runs/8857639618/job/24325344540#step:6:2291). To be consistent, I've updated all images to use 1001.

### CODE REVIEW

**Comment by hugovk** [comment]
Ignoring the failures for a moment, the build time for ubuntu-22.04-jammy-arm64v8 -> ubuntu-24.04-noble-arm64v8 is now very long: 26m -> 2h 3m.

Let's stick with 22.04 for at least this one.

---

For the manylinux ones:

> docker: Error response from daemon: pull access denied for pythonpillow/ubuntu-24.04-noble-amd64, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

Let's check those after merging so that image has been published.

**Comment by radarhere** [comment]
Ok. I've restored 22.04 arm64v8, and created https://github.com/python-pillow/Pillow/pull/8024 to increase the timeout to allow valgrind to pass.

**Comment by hugovk** [comment]
Valgrind is now the slowest one and has increased from 1h9m to 1h30m with 24.04. Let's stay on 22.04 a bit longer there too.

**Comment by radarhere** [comment]
Ok, done.

**Comment by hugovk** [comment]
Thanks!

This maybe wasn't very clear:

> For the manylinux ones:
> 
> > docker: Error response from daemon: pull access denied for pythonpillow/ubuntu-24.04-noble-amd64, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
> 
> Let's check those after merging so that image has been published.

I meant: let's revert these, merge, and do those in a followup. So we can make sure they pass before merging.

**Comment by hugovk** [comment]
Thank you very much!

**Pull request merged**
